/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ISNXFlashLoanTool,
  ISNXFlashLoanToolInterface,
} from "../ISNXFlashLoanTool";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "sUSDAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "snxAmount",
        type: "uint256",
      },
    ],
    name: "Burn",
    type: "event",
  },
  {
    inputs: [],
    name: "approvedExchange",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "sUSDAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "snxAmount",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "exchangeData",
        type: "bytes",
      },
    ],
    name: "burn",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ISNXFlashLoanTool__factory {
  static readonly abi = _abi;
  static createInterface(): ISNXFlashLoanToolInterface {
    return new utils.Interface(_abi) as ISNXFlashLoanToolInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISNXFlashLoanTool {
    return new Contract(address, _abi, signerOrProvider) as ISNXFlashLoanTool;
  }
}
