/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface IExchangeRatesInterface extends ethers.utils.Interface {
  functions: {
    "aggregatorWarningFlags()": FunctionFragment;
    "aggregators(bytes32)": FunctionFragment;
    "anyRateIsInvalid(bytes32[])": FunctionFragment;
    "canFreezeRate(bytes32)": FunctionFragment;
    "currenciesUsingAggregator(address)": FunctionFragment;
    "currentRoundForRate(bytes32)": FunctionFragment;
    "effectiveValue(bytes32,uint256,bytes32)": FunctionFragment;
    "effectiveValueAndRates(bytes32,uint256,bytes32)": FunctionFragment;
    "effectiveValueAtRound(bytes32,uint256,bytes32,uint256,uint256)": FunctionFragment;
    "freezeRate(bytes32)": FunctionFragment;
    "getCurrentRoundId(bytes32)": FunctionFragment;
    "getLastRoundIdBeforeElapsedSecs(bytes32,uint256,uint256,uint256)": FunctionFragment;
    "inversePricing(bytes32)": FunctionFragment;
    "lastRateUpdateTimes(bytes32)": FunctionFragment;
    "oracle()": FunctionFragment;
    "rateAndInvalid(bytes32)": FunctionFragment;
    "rateAndTimestampAtRound(bytes32,uint256)": FunctionFragment;
    "rateAndUpdatedTime(bytes32)": FunctionFragment;
    "rateForCurrency(bytes32)": FunctionFragment;
    "rateIsFlagged(bytes32)": FunctionFragment;
    "rateIsFrozen(bytes32)": FunctionFragment;
    "rateIsInvalid(bytes32)": FunctionFragment;
    "rateIsStale(bytes32)": FunctionFragment;
    "rateStalePeriod()": FunctionFragment;
    "ratesAndInvalidForCurrencies(bytes32[])": FunctionFragment;
    "ratesAndUpdatedTimeForCurrencyLastNRounds(bytes32,uint256)": FunctionFragment;
    "ratesForCurrencies(bytes32[])": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "aggregatorWarningFlags",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "aggregators",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "anyRateIsInvalid",
    values: [BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "canFreezeRate",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "currenciesUsingAggregator",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "currentRoundForRate",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "effectiveValue",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "effectiveValueAndRates",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "effectiveValueAtRound",
    values: [BytesLike, BigNumberish, BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "freezeRate",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentRoundId",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getLastRoundIdBeforeElapsedSecs",
    values: [BytesLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "inversePricing",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastRateUpdateTimes",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "oracle", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "rateAndInvalid",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rateAndTimestampAtRound",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rateAndUpdatedTime",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rateForCurrency",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rateIsFlagged",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rateIsFrozen",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rateIsInvalid",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rateIsStale",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rateStalePeriod",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ratesAndInvalidForCurrencies",
    values: [BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "ratesAndUpdatedTimeForCurrencyLastNRounds",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "ratesForCurrencies",
    values: [BytesLike[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "aggregatorWarningFlags",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "aggregators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "anyRateIsInvalid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "canFreezeRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currenciesUsingAggregator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentRoundForRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "effectiveValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "effectiveValueAndRates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "effectiveValueAtRound",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "freezeRate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentRoundId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLastRoundIdBeforeElapsedSecs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "inversePricing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastRateUpdateTimes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "oracle", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "rateAndInvalid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rateAndTimestampAtRound",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rateAndUpdatedTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rateForCurrency",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rateIsFlagged",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rateIsFrozen",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rateIsInvalid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rateIsStale",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rateStalePeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ratesAndInvalidForCurrencies",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ratesAndUpdatedTimeForCurrencyLastNRounds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ratesForCurrencies",
    data: BytesLike
  ): Result;

  events: {};
}

export class IExchangeRates extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IExchangeRatesInterface;

  functions: {
    aggregatorWarningFlags(overrides?: CallOverrides): Promise<[string]>;

    aggregators(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    anyRateIsInvalid(
      currencyKeys: BytesLike[],
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    canFreezeRate(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    currenciesUsingAggregator(
      aggregator: string,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    currentRoundForRate(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    effectiveValue(
      sourceCurrencyKey: BytesLike,
      sourceAmount: BigNumberish,
      destinationCurrencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { value: BigNumber }>;

    effectiveValueAndRates(
      sourceCurrencyKey: BytesLike,
      sourceAmount: BigNumberish,
      destinationCurrencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        value: BigNumber;
        sourceRate: BigNumber;
        destinationRate: BigNumber;
      }
    >;

    effectiveValueAtRound(
      sourceCurrencyKey: BytesLike,
      sourceAmount: BigNumberish,
      destinationCurrencyKey: BytesLike,
      roundIdForSrc: BigNumberish,
      roundIdForDest: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { value: BigNumber }>;

    freezeRate(
      currencyKey: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getCurrentRoundId(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getLastRoundIdBeforeElapsedSecs(
      currencyKey: BytesLike,
      startingRoundId: BigNumberish,
      startingTimestamp: BigNumberish,
      timediff: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    inversePricing(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, boolean, boolean] & {
        entryPoint: BigNumber;
        upperLimit: BigNumber;
        lowerLimit: BigNumber;
        frozenAtUpperLimit: boolean;
        frozenAtLowerLimit: boolean;
      }
    >;

    lastRateUpdateTimes(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    oracle(overrides?: CallOverrides): Promise<[string]>;

    rateAndInvalid(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber, boolean] & { rate: BigNumber; isInvalid: boolean }>;

    rateAndTimestampAtRound(
      currencyKey: BytesLike,
      roundId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber] & { rate: BigNumber; time: BigNumber }>;

    rateAndUpdatedTime(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber] & { rate: BigNumber; time: BigNumber }>;

    rateForCurrency(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    rateIsFlagged(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    rateIsFrozen(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    rateIsInvalid(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    rateIsStale(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    rateStalePeriod(overrides?: CallOverrides): Promise<[BigNumber]>;

    ratesAndInvalidForCurrencies(
      currencyKeys: BytesLike[],
      overrides?: CallOverrides
    ): Promise<
      [BigNumber[], boolean] & { rates: BigNumber[]; anyRateInvalid: boolean }
    >;

    ratesAndUpdatedTimeForCurrencyLastNRounds(
      currencyKey: BytesLike,
      numRounds: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber[], BigNumber[]] & { rates: BigNumber[]; times: BigNumber[] }
    >;

    ratesForCurrencies(
      currencyKeys: BytesLike[],
      overrides?: CallOverrides
    ): Promise<[BigNumber[]]>;
  };

  aggregatorWarningFlags(overrides?: CallOverrides): Promise<string>;

  aggregators(
    currencyKey: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  anyRateIsInvalid(
    currencyKeys: BytesLike[],
    overrides?: CallOverrides
  ): Promise<boolean>;

  canFreezeRate(
    currencyKey: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  currenciesUsingAggregator(
    aggregator: string,
    overrides?: CallOverrides
  ): Promise<string[]>;

  currentRoundForRate(
    currencyKey: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  effectiveValue(
    sourceCurrencyKey: BytesLike,
    sourceAmount: BigNumberish,
    destinationCurrencyKey: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  effectiveValueAndRates(
    sourceCurrencyKey: BytesLike,
    sourceAmount: BigNumberish,
    destinationCurrencyKey: BytesLike,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber] & {
      value: BigNumber;
      sourceRate: BigNumber;
      destinationRate: BigNumber;
    }
  >;

  effectiveValueAtRound(
    sourceCurrencyKey: BytesLike,
    sourceAmount: BigNumberish,
    destinationCurrencyKey: BytesLike,
    roundIdForSrc: BigNumberish,
    roundIdForDest: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  freezeRate(
    currencyKey: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getCurrentRoundId(
    currencyKey: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getLastRoundIdBeforeElapsedSecs(
    currencyKey: BytesLike,
    startingRoundId: BigNumberish,
    startingTimestamp: BigNumberish,
    timediff: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  inversePricing(
    currencyKey: BytesLike,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber, boolean, boolean] & {
      entryPoint: BigNumber;
      upperLimit: BigNumber;
      lowerLimit: BigNumber;
      frozenAtUpperLimit: boolean;
      frozenAtLowerLimit: boolean;
    }
  >;

  lastRateUpdateTimes(
    currencyKey: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  oracle(overrides?: CallOverrides): Promise<string>;

  rateAndInvalid(
    currencyKey: BytesLike,
    overrides?: CallOverrides
  ): Promise<[BigNumber, boolean] & { rate: BigNumber; isInvalid: boolean }>;

  rateAndTimestampAtRound(
    currencyKey: BytesLike,
    roundId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber] & { rate: BigNumber; time: BigNumber }>;

  rateAndUpdatedTime(
    currencyKey: BytesLike,
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber] & { rate: BigNumber; time: BigNumber }>;

  rateForCurrency(
    currencyKey: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  rateIsFlagged(
    currencyKey: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  rateIsFrozen(
    currencyKey: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  rateIsInvalid(
    currencyKey: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  rateIsStale(
    currencyKey: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  rateStalePeriod(overrides?: CallOverrides): Promise<BigNumber>;

  ratesAndInvalidForCurrencies(
    currencyKeys: BytesLike[],
    overrides?: CallOverrides
  ): Promise<
    [BigNumber[], boolean] & { rates: BigNumber[]; anyRateInvalid: boolean }
  >;

  ratesAndUpdatedTimeForCurrencyLastNRounds(
    currencyKey: BytesLike,
    numRounds: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber[], BigNumber[]] & { rates: BigNumber[]; times: BigNumber[] }
  >;

  ratesForCurrencies(
    currencyKeys: BytesLike[],
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  callStatic: {
    aggregatorWarningFlags(overrides?: CallOverrides): Promise<string>;

    aggregators(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    anyRateIsInvalid(
      currencyKeys: BytesLike[],
      overrides?: CallOverrides
    ): Promise<boolean>;

    canFreezeRate(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    currenciesUsingAggregator(
      aggregator: string,
      overrides?: CallOverrides
    ): Promise<string[]>;

    currentRoundForRate(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    effectiveValue(
      sourceCurrencyKey: BytesLike,
      sourceAmount: BigNumberish,
      destinationCurrencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    effectiveValueAndRates(
      sourceCurrencyKey: BytesLike,
      sourceAmount: BigNumberish,
      destinationCurrencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        value: BigNumber;
        sourceRate: BigNumber;
        destinationRate: BigNumber;
      }
    >;

    effectiveValueAtRound(
      sourceCurrencyKey: BytesLike,
      sourceAmount: BigNumberish,
      destinationCurrencyKey: BytesLike,
      roundIdForSrc: BigNumberish,
      roundIdForDest: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    freezeRate(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    getCurrentRoundId(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getLastRoundIdBeforeElapsedSecs(
      currencyKey: BytesLike,
      startingRoundId: BigNumberish,
      startingTimestamp: BigNumberish,
      timediff: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    inversePricing(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, boolean, boolean] & {
        entryPoint: BigNumber;
        upperLimit: BigNumber;
        lowerLimit: BigNumber;
        frozenAtUpperLimit: boolean;
        frozenAtLowerLimit: boolean;
      }
    >;

    lastRateUpdateTimes(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    oracle(overrides?: CallOverrides): Promise<string>;

    rateAndInvalid(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber, boolean] & { rate: BigNumber; isInvalid: boolean }>;

    rateAndTimestampAtRound(
      currencyKey: BytesLike,
      roundId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber] & { rate: BigNumber; time: BigNumber }>;

    rateAndUpdatedTime(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber] & { rate: BigNumber; time: BigNumber }>;

    rateForCurrency(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    rateIsFlagged(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    rateIsFrozen(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    rateIsInvalid(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    rateIsStale(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    rateStalePeriod(overrides?: CallOverrides): Promise<BigNumber>;

    ratesAndInvalidForCurrencies(
      currencyKeys: BytesLike[],
      overrides?: CallOverrides
    ): Promise<
      [BigNumber[], boolean] & { rates: BigNumber[]; anyRateInvalid: boolean }
    >;

    ratesAndUpdatedTimeForCurrencyLastNRounds(
      currencyKey: BytesLike,
      numRounds: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber[], BigNumber[]] & { rates: BigNumber[]; times: BigNumber[] }
    >;

    ratesForCurrencies(
      currencyKeys: BytesLike[],
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;
  };

  filters: {};

  estimateGas: {
    aggregatorWarningFlags(overrides?: CallOverrides): Promise<BigNumber>;

    aggregators(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    anyRateIsInvalid(
      currencyKeys: BytesLike[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    canFreezeRate(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    currenciesUsingAggregator(
      aggregator: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    currentRoundForRate(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    effectiveValue(
      sourceCurrencyKey: BytesLike,
      sourceAmount: BigNumberish,
      destinationCurrencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    effectiveValueAndRates(
      sourceCurrencyKey: BytesLike,
      sourceAmount: BigNumberish,
      destinationCurrencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    effectiveValueAtRound(
      sourceCurrencyKey: BytesLike,
      sourceAmount: BigNumberish,
      destinationCurrencyKey: BytesLike,
      roundIdForSrc: BigNumberish,
      roundIdForDest: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    freezeRate(
      currencyKey: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getCurrentRoundId(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getLastRoundIdBeforeElapsedSecs(
      currencyKey: BytesLike,
      startingRoundId: BigNumberish,
      startingTimestamp: BigNumberish,
      timediff: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    inversePricing(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    lastRateUpdateTimes(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    oracle(overrides?: CallOverrides): Promise<BigNumber>;

    rateAndInvalid(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    rateAndTimestampAtRound(
      currencyKey: BytesLike,
      roundId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    rateAndUpdatedTime(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    rateForCurrency(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    rateIsFlagged(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    rateIsFrozen(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    rateIsInvalid(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    rateIsStale(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    rateStalePeriod(overrides?: CallOverrides): Promise<BigNumber>;

    ratesAndInvalidForCurrencies(
      currencyKeys: BytesLike[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    ratesAndUpdatedTimeForCurrencyLastNRounds(
      currencyKey: BytesLike,
      numRounds: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    ratesForCurrencies(
      currencyKeys: BytesLike[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    aggregatorWarningFlags(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    aggregators(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    anyRateIsInvalid(
      currencyKeys: BytesLike[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    canFreezeRate(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    currenciesUsingAggregator(
      aggregator: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    currentRoundForRate(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    effectiveValue(
      sourceCurrencyKey: BytesLike,
      sourceAmount: BigNumberish,
      destinationCurrencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    effectiveValueAndRates(
      sourceCurrencyKey: BytesLike,
      sourceAmount: BigNumberish,
      destinationCurrencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    effectiveValueAtRound(
      sourceCurrencyKey: BytesLike,
      sourceAmount: BigNumberish,
      destinationCurrencyKey: BytesLike,
      roundIdForSrc: BigNumberish,
      roundIdForDest: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    freezeRate(
      currencyKey: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getCurrentRoundId(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getLastRoundIdBeforeElapsedSecs(
      currencyKey: BytesLike,
      startingRoundId: BigNumberish,
      startingTimestamp: BigNumberish,
      timediff: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    inversePricing(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    lastRateUpdateTimes(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    oracle(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    rateAndInvalid(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    rateAndTimestampAtRound(
      currencyKey: BytesLike,
      roundId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    rateAndUpdatedTime(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    rateForCurrency(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    rateIsFlagged(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    rateIsFrozen(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    rateIsInvalid(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    rateIsStale(
      currencyKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    rateStalePeriod(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    ratesAndInvalidForCurrencies(
      currencyKeys: BytesLike[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ratesAndUpdatedTimeForCurrencyLastNRounds(
      currencyKey: BytesLike,
      numRounds: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ratesForCurrencies(
      currencyKeys: BytesLike[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
